### PR TITLE
Fix bug in 'safe_parse' function in Dig plugin

### PR DESCRIPTION
**Pull request by r7-kszczepanskagorna**
## Proposed Changes
Fix bug in 'safe_parse' function in Dig plugin

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://komand.github.io/python/style.html)

- [ ] For dependencies, pin [OS package](https://komand.github.io/python/style.html#dockerfile) and [Python package](https://komand.github.io/python/style.html#requirements-txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://komand.github.io/python/sdk.html#sdk-versions) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://komand.github.io/python/error_handling.html#plugin-exceptions) and [ConnectionTestException](https://komand.github.io/python/error_handling.html#connection-exceptions)
- [ ] For logging, use [self.logger](https://komand.github.io/python/sdk.html#logging)
- [ ] For docs, use [changelog style](https://komand.github.io/python/style.html#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://komand.github.io/python/style.html#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Run

<details>

```
{
  "body": {
    "log": "rapid7/Dig:1.0.7. Step name: forward\nExecuting command /usr/bin/dig rapid7.com ANY\n",
    "meta": {},
    "output": {
      "all_answers": [
        "ns-1390.awsdns-45.org",
        "ns-1653.awsdns-14.co.uk",
        "ns-439.awsdns-54.com",
        "86400",
        "ns-739.awsdns-28.net",
        "NO MATCHES FOUND",
        "SECTION:",
        "ns-1653.awsdns-14.co.uk",
        "ns-439.awsdns-54.com",
        "ns-739.awsdns-28.net",
        "ns-1390.awsdns-45.org"
      ],
      "answer": "ns-1390.awsdns-45.org",
      "fulloutput": "\n; \u003c\u003c\u003e\u003e DiG 9.14.12 \u003c\u003c\u003e\u003e rapid7.com ANY\n;; global options: +cmd\n;; Got answer:\n;; -\u003e\u003eHEADER\u003c\u003c- opcode: QUERY, status: NOERROR, id: 34670\n;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 4, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;rapid7.com.\t\t\tIN\tANY\n\n;; ANSWER SECTION:\nrapid7.com.\t\t627\tIN\tNS\tns-1390.awsdns-45.org.\nrapid7.com.\t\t627\tIN\tNS\tns-1653.awsdns-14.co.uk.\nrapid7.com.\t\t627\tIN\tNS\tns-439.awsdns-54.com.\nrapid7.com.\t\t154\tIN\tSOA\tns-1653.awsdns-14.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400\nrapid7.com.\t\t627\tIN\tNS\tns-739.awsdns-28.net.\n\n;; AUTHORITY SECTION:\nrapid7.com.\t\t627\tIN\tNS\tns-1653.awsdns-14.co.uk.\nrapid7.com.\t\t627\tIN\tNS\tns-439.awsdns-54.com.\nrapid7.com.\t\t627\tIN\tNS\tns-739.awsdns-28.net.\nrapid7.com.\t\t627\tIN\tNS\tns-1390.awsdns-45.org.\n\n;; Query time: 3 msec\n;; SERVER: 10.0.2.3#53(10.0.2.3)\n;; WHEN: Thu Sep 24 20:20:46 UTC 2020\n;; MSG SIZE  rcvd: 282\n\n",
      "last_answer": "ns-1390.awsdns-45.org",
      "nameserver": "10.0.2.3",
      "question": "rapid7.com",
      "status": "NOERROR"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/dig:1.0.7 --debug run < tests/forward.json
</summary>
</details>

<details>

```
{
INFO[0000] Running command:  docker run --rm -i rapid7/dig:1.0.7 run < tests/forward.json
rapid7/Dig:1.0.7. Step name: forward
Executing command /usr/bin/dig rapid7.com ANY
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 307, in handle_step
    output = self.start_step(
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 428, in start_step
    output = func(params)
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/actions/forward/action.py", line 39, in run
    ans = [util.safe_parse(re.search(r'\s(\S+)$', answer)) for answer in ans]
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/actions/forward/action.py", line 39, in <listcomp>
    ans = [util.safe_parse(re.search(r'\s(\S+)$', answer)) for answer in ans]
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/util/util.py", line 10, in safe_parse
    regex = regex.group(1) if re else "NO MATCHES FOUND"
AttributeError: 'NoneType' object has no attribute 'group'
{"body": {"log": "rapid7/Dig:1.0.7. Step name: forward\nExecuting command /usr/bin/dig rapid7.com ANY\n'NoneType' object has no attribute 'group'\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 307, in handle_step\n    output = self.start_step(\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 428, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/actions/forward/action.py\", line 39, in run\n    ans = [util.safe_parse(re.search(r'\\s(\\S+)$', answer)) for answer in ans]\n  File \"/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/actions/forward/action.py\", line 39, in <listcomp>\n    ans = [util.safe_parse(re.search(r'\\s(\\S+)$', answer)) for answer in ans]\n  File \"/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/util/util.py\", line 10, in safe_parse\n    regex = regex.group(1) if re else \"NO MATCHES FOUND\"\nAttributeError: 'NoneType' object has no attribute 'group'\n", "status": "error", "meta": {}, "error": "'NoneType' object has no attribute 'group'"}, "version": "v1", "type": "action_event"}
Traceback (most recent call last):
  File "/usr/local/bin/komand_dig", line 4, in <module>
    __import__('pkg_resources').run_script('dig-rapid7-plugin==1.0.7', 'komand_dig')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/EGG-INFO/scripts/komand_dig", line 48, in <module>
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/EGG-INFO/scripts/komand_dig", line 44, in main
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 254, in run
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 154, in run_step
    return self.execute_step(is_test=False, is_debug=args.debug)
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 151, in execute_step
    raise exception
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 141, in execute_step
    output = self.plugin.handle_step(msg, is_test=is_test,
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 342, in handle_step
    raise LoggedException(ex, output)
insightconnect_plugin_runtime.exceptions.LoggedException: 'NoneType' object has no attribute 'group'
}

```

<summary>
test failed - before changes
</summary>
</details>

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator ExceptionValidator
[*] Executing validator CredentialsValidator
[*] Executing validator PasswordValidator
[*] Executing validator PrintValidator
[*] Executing validator ConfidentialValidator
[*] Executing validator DockerValidator
[*] Executing validator URLValidator
WARNING: URLs found that return a 4xx code. Verify they are publicly accessible and if not, update with a working URL.
violation: help.md[167]: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
violation: help.md[217]: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
[*] Plugin successfully validated!

----
[*] Total time elapsed: 40504.518ms

```

<summary>
icon-validate --all .
</summary>
</details>

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Plugin successfully validated!

----
[*] Total time elapsed: 1078.954ms

[*] Validating spec with js-yaml
[SUCCESS] Passes js-yaml spec check


[*] Validating markdown...
[SUCCESS] Passes markdown linting

[*] Validating python files for style...
[SUCCESS] Passes flake8 linting

[*] Validating python files for security vulnerabilities...
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.7.3
Run started:2020-09-24 20:23:16.320258

Test results:
        No issues identified.

Code scanned:
        Total lines of code: 339
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 0.0
Files skipped (0):
[SUCCESS] Passes bandit security checks

[*] Checking for typos with Misspell...
[SUCCESS] Passes Misspell check

```

<summary>
make validate
</summary>
</details>

### CODE REVIEW

**Comment by mrinehart-r7** [comment]
@r7-kszczepanskagorna I was able to cause the plugin to fail with the following JSON sample used as input:
```
{
  "body": {
    "action": "forward",
    "connection": null,
    "input": {
      "domain": "sdf",
      "query": "ANY",
      "resolver": ""
    },
    "meta": {}
  },
  "type": "action_start",
  "version": "v1"
}
```
Error:
```
⇒  icon-plugin run -R tests/forward.json
INFO[0000] Running command:  docker run --rm -i rapid7/dig:1.0.7 run < tests/forward.json
rapid7/Dig:1.0.7. Step name: forward
Executing command /usr/bin/dig sdf ANY
'>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 307, in handle_step
    output = self.start_step(
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 428, in start_step
    output = func(params)
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/actions/forward/action.py", line 22, in run
    command_output = util.execute_command(self.logger, cmd, r'ANSWER SECTION:\n(.*)\n\n;;', re.DOTALL)
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/util/util.py", line 36, in execute_command
    if answers > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
{"body": {"log": "rapid7/Dig:1.0.7. Step name: forward\nExecuting command /usr/bin/dig sdf ANY\n'>' not supported between instances of 'str' and 'int'\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 307, in handle_step\n    output = self.start_step(\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 428, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/actions/forward/action.py\", line 22, in run\n    command_output = util.execute_command(self.logger, cmd, r'ANSWER SECTION:\\n(.*)\\n\\n;;', re.DOTALL)\n  File \"/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/komand_dig/util/util.py\", line 36, in execute_command\n    if answers > 0:\nTypeError: '>' not supported between instances of 'str' and 'int'\n", "status": "error", "meta": {}, "error": "'>' not supported between instances of 'str' and 'int'"}, "version": "v1", "type": "action_event"}
Traceback (most recent call last):
  File "/usr/local/bin/komand_dig", line 4, in <module>
    __import__('pkg_resources').run_script('dig-rapid7-plugin==1.0.7', 'komand_dig')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/EGG-INFO/scripts/komand_dig", line 48, in <module>
  File "/usr/local/lib/python3.8/site-packages/dig_rapid7_plugin-1.0.7-py3.8.egg/EGG-INFO/scripts/komand_dig", line 44, in main
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 254, in run
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 154, in run_step
    return self.execute_step(is_test=False, is_debug=args.debug)
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 151, in execute_step
    raise exception
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/cli.py", line 141, in execute_step
    output = self.plugin.handle_step(msg, is_test=is_test,
  File "/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.1.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py", line 342, in handle_step
    raise LoggedException(ex, output)
insightconnect_plugin_runtime.exceptions.LoggedException: '>' not supported between instances of 'str' and 'int'
```

**Review by mrinehart-r7 — CHANGES_REQUESTED** [review]
Need to fix bug in comment

**Comment by jschipp-r7** [comment]
@r7-kszczepanskagorna need to address @mrinehart-r7 's comment

**Comment by r7-kszczepanskagorna** [comment]
@jschipp-r7 PR #701 resolve problems from @mrinehart-r7  comment. I will merge #701 to this PR and let you know when I do it :)

**Review by ncramer-r7 — APPROVED** [review]

**Review by jschipp-r7 — APPROVED** [review]

**Pull request merged**
