### PR TITLE
Jira: Fix bug in "Get Comments", failing normalize_user in Jira Cloud

### PR DESCRIPTION
**Pull request by ax-rpipkin**
### Description

Describe the proposed changes:

- Pass Jira client `is_cloud` boolean into `normalize_comment` function
- Pass `is_cloud` from `normalize_comment` as is required for dependency `normalize_user`

## PR Requirements

Developers, verify you have completed the following items by checking them off:

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [x] Unit tests written for any new or updated code
  - Note: unnecessary to adjust, as it does not introduce any new functionality.

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [x] Screenshot of job output with the plugin changes
- [x] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

  - *N/A* : minor edits to existing codebase

### Functional Checklist
- [X] Work fully completed
- [X] Functional

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

### CODE REVIEW

**Comment by mrinehart-r7** [comment]
LGTM, will merge this when our checks start working again @ax-rpipkin

**Comment by pmara-r7** [comment]
@mrinehart-r7 any idea why these checks aren't running?

**Comment by mrinehart-r7** [comment]
> @mrinehart-r7 any idea why these checks aren't running?

It could be due to the commits coming in from a fork - our CI checks don't work the greatest with forks.

**Comment by mberezin-r7** [comment]
I validated the jira plugin locally on this PR branch and it passes.

```
$ pwd 
/Users/mberezin/go/src/github.com/rapid7/insightconnect-plugins/plugins/jira
$ icon-validate .
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Plugin successfully validated!

----
[*] Total time elapsed: 907.1329999999999ms
```

**Review by mberezin-r7 — APPROVED** [review]

**Review by pmara-r7 — APPROVED** [review]
Approving per a team review, and @mberezin-r7 validation

**Pull request merged**
