### PR TITLE
[MC-524] [MC-1175] Powershell, Python3 fix credentials issue

### PR DESCRIPTION
**Pull request by mgrandys-r7**
### Description

Describe the proposed changes:

  - Fix credentials in actions issue in Powershell and Python plugins

## PR Requirements

Developers, verify you have completed the following items by checking them off:

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting..\nrapid7/PowerShell:2.2.0. Step name: execute_script\nRunning on local VM\n",
    "status": "ok",
    "meta": {},
    "output": {
      "stdout": "\nUserName                         Password\n--------                         --------\nexample_user System.Security.SecureString\ns1e2c3r4e5t67k8e9y\n\n",
      "stderr": ""
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i rapid7/powershell:3.0.0 run < tests/execute_script.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting..\nrapid7/PowerShell:3.0.0. Step name: powershell_string\nRunning on local VM\n",
    "status": "ok",
    "meta": {},
    "output": {
      "stdout": "\nMonday, 06 June 2022 11:01:14\n\nUserName : example_user\nPassword : System.Security.SecureString\n\ns1e2c3r4e5t67k8e9y\n\n",
      "stderr": ""
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i rapid7/powershell:3.0.0 run < tests/powershell_string.json
</summary>
</details>

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../../tools/Makefiles/Helpers.mk ../../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator CloudReadyValidator
[*] Executing validator SupportedVersionValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator HelpExampleValidator
[*] Executing validator Version Increment Validator
[*] Plugin failed validation! The following validation errors occurred:

Validator "HelpValidator" failed!
        Cause: Help section contains non-matching title in line: |add_credentials_to_script|boolean|None|True|This parameter indicates whether `Username and Password` and `Secret Key` action parameters will be added to script as powershell variables or not. Choosing `True` creates powershell variables (`$username`, `$password` and `$secret_key`) which you can use in your script in `Script` parameter. If you don't need those credentials choose `False` and provide some random values for `Username and Password` and `Secret Key` parameters|None|False|

Validator "HelpExampleValidator" failed!
        Cause: Invalid JSON example identified in Example input of action titled PowerShell String. Please correct the JSON example in help.md.
        Invalid JSON example identified in Example input of action titled PowerShell String. Please correct the JSON example in help.md.
        Invalid JSON example identified in Example input of action titled Input. Please correct the JSON example in help.md.
        Invalid JSON example identified in Example input of action titled Input. Please correct the JSON example in help.md.


----
[*] Total time elapsed: 1642.917ms
make: *** [../../tools/Makefiles/Helpers.mk:15: validate] Error 1
```

<summary>
make validate
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Python 3 Script:3.0.0. Step name: run\nInput: (below)\n\n{'some_input': 'example_param'}\n\nFunction: (below)\n\ndef run(params={}):\n\tprint(username, password, secret_key)\n\treturn {'result1': 'example output 1', 'result2': 'example output 2'}\n\n",
    "status": "ok",
    "meta": {},
    "output": {
      "result1": "example output 1",
      "result2": "example output 2"
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i rapid7/python_3_script:3.0.0 run < tests/run.json
</summary>
</details>

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../../tools/Makefiles/Helpers.mk ../../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator CloudReadyValidator
[*] Executing validator SupportedVersionValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator HelpExampleValidator
[*] Executing validator Version Increment Validator
[*] Plugin failed validation! The following validation errors occurred:

Validator "HelpExampleValidator" failed!
        Cause: Invalid JSON example identified in Example input of action titled Run Function. Please correct the JSON example in help.md.
        Invalid JSON example identified in Example input of action titled Run Function. Please correct the JSON example in help.md.
        Improperly formatted JSON example identified in Example input of action titled Run Function. Please updated the JSON example in help.md with 2 space indentation.
        Improperly formatted JSON example identified in Example input of action titled Run Function. Please updated the JSON example in help.md with 2 space indentation.
        Improperly formatted JSON example identified in Example input of action titled Run Function. Please updated the JSON example in help.md with 2 space indentation.

Validator "Version Increment Validator" failed!
        Cause: Input has been added or changed to required in add_credentials_to_script without a major version increment. Please change the plugin version to 4.0.0


----
[*] Total time elapsed: 2600.433ms
make: *** [../../tools/Makefiles/Helpers.mk:15: validate] Error 1
```

<summary>
make validate
</summary>
</details>

### CODE REVIEW

**Comment by mgrandys-r7** [comment]
PluginValidator keeps failing for:
Validator "HelpValidator" failed! 
	Cause: Help section contains non-matching title in line: |add_credentials_to_script|boolean|None|True|This parameter indicates whether `Username and Password` and `Secret Key` action parameters will be added to script as powershell variables or not. Choosing `True` creates powershell variables (`$username`, `$password` and `$secret_key`) which you can use in your script in `Script` parameter. If you don't need those credentials choose `False` and provide some random values for `Username and Password` and `Secret Key` parameters|None|False|

@blaxminarayan-r7 Could you or someone from your team please support me here? I have checked few times if this line is correct in help.md and it is. Running `make regenerate` doesn't change this line so I don't know what is the reason of this error.

**Comment by mgrandys-r7** [comment]
Also there is an unit tests error on GH while locally all tests pass

**Comment by mgrandys-r7** [comment]
Plugin Validator issue fixed

**Review by dsliwinski-r7 — CHANGES_REQUESTED** [review]

**Review by akarolik-r7 — APPROVED** [review]

**Review by dsliwinski-r7 — APPROVED** [review]

**Comment by mgrandys-r7** [comment]
Plugins tested on Platform.

Python:
- https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/workflows/details/530b208f-8d05-4333-8cac-c0d2ca8f91a5/versions/92fb5be6-71c5-4a46-82aa-81c9857984a4
- https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/jobs/details/a447e9de-159e-4ef1-bc6d-5073efebef08

Powershell:
- https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/workflows/details/5fbb9e55-0bee-4566-b9e2-30fa8e1fda93/versions/84357be9-f261-4f05-8134-7c21b2baf2df
- https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/jobs/details/673c4812-989f-4684-9097-36f914b545a3

**Comment by mgrandys-r7** [comment]
@blaxminarayan-r7 
Closed Pull request as the requirements has changed and credentials will be implemented in connections - not actions

**Pull request closed without merging**
