### PR TITLE
Trend Micro Vision One Insight Connect Plugin pre-production fixup

### PR DESCRIPTION
**Pull request by pedro-securo**
### Description

Describe the proposed changes:

  - In the live demo of this plugin a bug was found which is fixed by this update.
  - There were also some further errors stemming from "make validate" and unit-tests, which are also fixed herein.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [x] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [x] Screenshot of job output with the plugin changes
- [x] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [x] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [x] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [x] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``rapid7/insightconnect-python-3-38-slim-plugin:{sdk-version-num}`` and ``rapid7/insightconnect-python-3-38-plugin:{sdk-version-num}``
- [x] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [x] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [x] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [x] For docs, validate markdown with ``insight-plugin validate`` which calls ``icon_validate`` to lint ``help.md``

### Functional Checklist
- [x] Work fully completed
- [x] Functional
  - [x] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `insight-plugin samples`
  - [x] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [x] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [x] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at end)
  - [x] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `insight-plugin validate` and make sure everything passes
2. Run the assessment tool: `insight-plugin run -A`. For single action validation: `insight-plugin run tests/{file}.json -A`
3. Copy (`insight-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

### CODE REVIEW

**Comment by pedro-securo** [comment]
Screenshot of the alert details properly populating the relevant fields and the values being correctly relayed to the next action in a workflow:
Screenshot 2023-08-01 at 15 39 54

**Comment by pedro-securo** [comment]
Output to Input in a workflow:
Screenshot 2023-08-01 at 15 44 21

**Comment by pedro-securo** [comment]
icon-plugin run -T all --debug --jq
INFO[0000] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/add_alert_note.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0007] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0007] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/add_to_block_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0015] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0015] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/add_to_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0023] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0023] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/add_to_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0031] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0031] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/collect_file.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0038] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0039] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/delete_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0046] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0046] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/disable_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0054] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0054] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/download_sandbox_analysis_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0063] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0063] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/download_sandbox_investigation_package.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0071] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0071] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/edit_alert_status.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0080] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0080] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/enable_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0088] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0088] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_alert_details.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0096] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0096] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_alert_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0104] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0104] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_endpoint_data.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0112] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0112] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0120] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0120] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_sandbox_analysis_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0129] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0130] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_sandbox_submission_status.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0138] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0138] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_sandbox_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0146] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0147] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0155] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0155] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/get_task_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0164] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0164] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/isolate_endpoint.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0172] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0172] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/quarantine_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0180] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0181] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/remove_from_block_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0189] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0189] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/remove_from_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0197] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0197] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/remove_from_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0205] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0206] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/reset_password_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0213] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0214] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/restore_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0222] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0222] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/restore_endpoint.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0230] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0230] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/sign_out_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0238] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0239] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/submit_file_to_sandbox.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0246] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0247] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/submit_urls_to_sandbox.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0255] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

INFO[0255] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug test < tests/terminate_process.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0263] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
null

**Comment by pedro-securo** [comment]
icon-plugin run -R all --debug --jq
INFO[0000] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/add_alert_note.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "location": "http://tmv1-mock.trendmicro.com/v3/workbench/alerts/2345245/notes/1",
  "note_id": "1",
  "result_code": "SUCCESS"
}

INFO[0007] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/add_to_block_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000007"
    },
    {
      "status": 202,
      "task_id": "00000007"
    }
  ]
}

INFO[0015] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/add_to_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 201,
      "task_id": "None"
    }
  ]
}

INFO[0023] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/add_to_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 201,
      "task_id": "None"
    }
  ]
}

INFO[0031] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/collect_file.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000003"
    }
  ]
}

INFO[0039] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/delete_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000001"
    }
  ]
}

INFO[0046] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/disable_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000009"
    }
  ]
}

INFO[0054] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/download_sandbox_analysis_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0062] JPP: unable to apply value to string: unexpected EOF 

ERRO[0062] JPP: unable to apply value to string: key not found 

INFO[0062] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/download_sandbox_investigation_package.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "file": {
    "content": "UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==",
    "filename": "Trend Micro Download Sandbox Investigation Package 01_08_2023_14_06_30.zip"
  }
}

INFO[0071] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/edit_alert_status.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "result_code": "SUCCESS"
}

INFO[0079] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/enable_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000010"
    }
  ]
}

INFO[0087] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_alert_details.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "alert_details": {
    "alert": {
"SANITIZED"
    }
  },
  "etag": "33a64df551425fcc55e4d42a148795d9f25f89d4"
}

INFO[0095] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_alert_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERRO[0103] JPP: unable to apply value to string: unexpected EOF 

ERRO[0103] JPP: unable to apply value to string: key not found 

INFO[0103] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_endpoint_data.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "endpoint_data": [
    {SANITIZED}
  ]
}

INFO[0112] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "exception_objects": [
    {
      "description": "object description",
      "last_modified_date_time": "2023-07-31T14:07:19Z",
      "type": "url",
      "value": "https://*.example.com/path1/*"
    }
  ]
}

INFO[0120] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_sandbox_analysis_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "analysis_completion_date_time": "2023-08-01T14:07:17Z",
  "arguments": "LS10ZXN0IA==",
  "detection_names": [
    "VAN_DROPPER.UMXX"
  ],
  "digest": {
    "md5": "4ac174730d4143a119037d9fda81c7a9",
    "sha1": "fb5608fa03de204a12fe1e9e5275e4a682107471",
    "sha256": "65b0f656e79ab84ca17807158e3eac206bd58be6689ddeb95956a48748d138f9"
  },
  "id": "234234",
  "risk_level": "high",
  "threat_types": [
    "Dropper"
  ],
  "true_file_type": "exe",
  "type": "file"
}

INFO[0128] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_sandbox_submission_status.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "action": "analyzeFile",
  "arguments": "LS10ZXN0IA==",
  "created_date_time": "2023-08-01T14:06:35Z",
  "digest": {
    "md5": "4ac174730d4143a119037d9fda81c7a9",
    "sha1": "fb5608fa03de204a12fe1e9e5275e4a682107471",
    "sha256": "65b0f656e79ab84ca17807158e3eac206bd58be6689ddeb95956a48748d138f9"
  },
  "error": {},
  "id": "234234",
  "is_cached": true,
  "last_action_date_time": "2023-08-01T14:06:35Z",
  "resource_location": "http://tmv1-mock.trendmicro.com/v3.0/sandbox/analysisResults/234234",
  "status": "succeeded"
}

INFO[0136] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_sandbox_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "sandbox_suspicious_list_resp": [
    {
      "analysis_completion_date_time": "2023-08-01T14:07:33Z",
      "expired_date_time": "2023-08-02T14:07:43Z",
      "risk_level": "high",
      "root_sha1": "fb5608fa03de204a12fe1e9e5275e4a682107471",
      "type": "ip",
      "value": "6.6.6.6"
    }
  ]
}

INFO[0144] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "suspicious_objects": [
    {
      "description": "object description",
      "expired_date_time": "2023-07-31T14:07:51Z",
      "in_exception_list": false,
      "last_modified_date_time": "2023-07-31T14:07:51Z",
      "risk_level": "high",
      "scan_action": "log",
      "type": "fileSha256",
      "value": "asidj123123jsdsidjsid123sidsidj123sss123s224212312312312312sdaas"
    }
  ]
}

INFO[0152] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/get_task_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "account": "test",
  "action": "isolate",
  "agent_guid": "",
  "created_date_time": "2023-08-01T14:06:59Z",
  "description": "task description",
  "endpoint_name": "",
  "expired_date_time": "",
  "file_path": "",
  "file_sha1": "",
  "file_sha256": "",
  "file_size": 0,
  "filename": "",
  "id": "00000004",
  "image_path": "",
  "last_action_date_time": "2023-08-01T14:06:59Z",
  "password": "",
  "pid": 0,
  "resource_location": "",
  "sandbox_task_id": "",
  "status": "succeeded",
  "tasks": [],
  "url": ""
}

INFO[0160] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/isolate_endpoint.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000004"
    }
  ]
}

INFO[0168] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/quarantine_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000002"
    }
  ]
}

INFO[0176] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/remove_from_block_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000008"
    }
  ]
}

INFO[0184] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/remove_from_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 204,
      "task_id": "None"
    }
  ]
}

INFO[0192] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/remove_from_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 204,
      "task_id": "None"
    }
  ]
}

INFO[0200] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/reset_password_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000011"
    }
  ]
}

INFO[0208] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/restore_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000003"
    }
  ]
}

INFO[0217] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/restore_endpoint.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000005"
    }
  ]
}

INFO[0225] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/sign_out_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000012"
    }
  ]
}

INFO[0233] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/submit_file_to_sandbox.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "arguments": "LS10ZXN0IA==",
  "digest": {
    "md5": "4ac174730d4143a119037d9fda81c7a9",
    "sha1": "fb5608fa03de204a12fe1e9e5275e4a682107471",
    "sha256": "65b0f656e79ab84ca17807158e3eac206bd58be6689ddeb95956a48748d138f9"
  },
  "id": "012e4eac-9bd9-4e89-95db-xyumvmz9pcuq"
}

INFO[0241] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/submit_urls_to_sandbox.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "submit_urls_resp": [
    {
      "digest": {
        "md5": "f3a2e1227de8d5ae7296665c1f34b28d",
        "sha1": "d79bff55069994b1c11f7856f9f029de36adfd8f",
        "sha256": "619a273ee4d25fb4aeb97e89c554fcfbdbc82e22d840cfdb364a8f1932f48160"
      },
      "id": "012e4eac-9bd9-4e89-95db-77e02f75a6f5",
      "status": 202,
      "task_id": "00000005",
      "url": "https://www.trendmicro.com"
    },
    {
      "digest": {
        "md5": "f3a2e1227de8d5ae7296665c1f34b28d",
        "sha1": "d79bff55069994b1c11f7856f9f029de36adfd8f",
        "sha256": "619a273ee4d25fb4aeb97e89c554fcfbdbc82e22d840cfdb364a8f1932f48160"
      },
      "id": "012e4eac-9bd9-4e89-95db-77e02f75a6f5",
      "status": 202,
      "task_id": "00000005",
      "url": "https://www.trendmicro.com"
    }
  ]
}

INFO[0249] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.1 --debug run < tests/terminate_process.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{
  "multi_response": [
    {
      "status": 202,
      "task_id": "00000006"
    }
  ]
}

**Comment by pedro-securo** [comment]
@dlaverty-r7 thanks for pointing that out. Should be good now.

**Review by dlaverty-r7 — APPROVED** [review]

**Review by cmcnally-r7 — APPROVED** [review]

**Review by igorski-r7 — APPROVED** [review]

**Review by TKuzas-R7 — APPROVED** [review]

**Comment by dlaverty-r7** [comment]
@pedro-securo , apologies I am just getting a chance to look at this again. Please rebase and to resolve the conflicts and I will get this merged. Thanks!

**Pull request merged**
